### ISSUE TITLE
Unable to login into the desktop from lightdm window

### ISSUE THREAD

**Issue by c02y** [EndeavourOS-Community-Editions/sway#16]
I install i3 as my WM first, then I follow the README git clone and `bash sway-install.sh`, logout or reboot, choose `sway` from the bar, type the password and enter, but fail to login into the desktop, choose the `i3` again, it works OK.

BTW:

I'm trying it in VirtualBox

**Comment by c02y** [comment]
No

I tried it in VirtualBox BTW.

**Comment by killajoe** [comment]
it seems sway/wayland has an issue with lightdm currently.. where others like GDm and sddm will work.. and indeed using startX if you have a .xinitrc to start sway

**Comment by c02y** [comment]
I tried sddm, there is only one white cursor and black screen.

I tried gdm, the result is the same as lightdm, it stays in lightdm login window nothing else.

I tried them in VirtualBox BTW(already followed https://discovery.endeavouros.com/applications/installing-endeavouros-on-virtualbox/2021/03/), maybe VirtualBox is the reason.

**Comment by OdiousImp2604** [comment]
Ah. Yes that could be the problem. They are always some problems with sway on a any emulator. Tinker around with the settings because it always different with everyone. Or perhaps try a QMEU based alternative? GNOME-BOXES or KVM. 

The sway edition is switching to ly soon which has been tested and works. Bare metal does work for ly and the emulator may or may not.

**Comment by killajoe** [comment]
> I tried sddm, there is only one white cursor and black screen.
> 
> I tried gdm, the result is the same as lightdm, it stays in lightdm login window nothing else.
> 
> I tried them in VirtualBox BTW(already followed https://discovery.endeavouros.com/applications/installing-endeavouros-on-virtualbox/2021/03/), maybe VirtualBox is the reason.

for me it works in Virtualbox but I have no cursor (it stays transparent) 
QEMU works better currently

**Comment by emield12** [comment]
I have the same problem while not using a VM. I have EndeavourOS I3 version and used the script to install sway. I tried to login with both lightdm & gdm and they don't work.

**Comment by killajoe** [comment]
i do create an altrernative starter for sway simply like so:
saved as` /usr/bin/sway-sleep` and make it executable (chmod +x)

```
#!/bin/bash
sleep 5
sway
```

while modify `/usr/share/wayland/sessions/sway.desktop` like so:

```
[Desktop Entry]
Name=Sway
Comment=An i3-compatible Wayland compositor
Exec=/usr/bin/sway-sleep
Type=Application
```

i can use every greeter and lightdm…

it seems that starting the wayland session is failing or not completed before sway tries to startup…

**Comment by killajoe** [comment]
> I tried sddm, there is only one white cursor and black screen.
> 
> I tried gdm, the result is the same as lightdm, it stays in lightdm login window nothing else.
> 
> I tried them in VirtualBox BTW(already followed https://discovery.endeavouros.com/applications/installing-endeavouros-on-virtualbox/2021/03/), maybe VirtualBox is the reason.

on VirtualBox (same for other VMs ) you need to make sure that 3d is enabled in settings

**Comment by c02y** [comment]
Are you sure once I enabled 3d, it will work OK? I said I followed the guideline in the link, if there is 3d in the link, then I already enabled it.
