### ISSUE TITLE
Sway config suddenly disappeared the next day

### ISSUE THREAD

**Issue by VNGamerGit** [EndeavourOS-Community-Editions/sway#17]
I just installed EndeavourOS yesterday (and pre-installed Sway along with it). I decided to copy the config file of Sway like what the Sway wiki said in order to edit the config file (https://github.com/swaywm/sway/wiki). Today, everything somehow reseted back to the normal config, abd I'm unable to open anything. Help?

**Comment by OdiousImp2604** [comment]
You have copied the original config of sway not the EndeavourOS one so now it is using that. To edit our sway config but go to ~/.config/sway and you'll see different files to edit different things.
