### ISSUE TITLE
How to reinstall this version of sway?

### ISSUE THREAD

**Issue by VNGamerGit** [EndeavourOS-Community-Editions/sway#18]

**Comment by OdiousImp2604** [comment]
Just run the install script again it will overwrite your old configs. 

```
cp -R .config/* ~/.config/

cp .profile ~/.profile

cp .gtkrc-2.0 ~/.gtkrc-2.0

chmod -R +x ~/.config/sway/scripts

chmod -R +x ~/.config/waybar/scripts

sudo pacman -Syu --needed --noconfirm - < packages-repository.txt

dbus-launch dconf load / < xed.dconf

```

**Comment by dvisan** [comment]
Tried sudo bash sway-install.sh while in my sway session. Did a sway reload after everything is still the same. Then I logged out f the session, logged back in and it's still the same. I don't know why the config file didn't overwrite anything.
