### ISSUE TITLE
[waybar] Weather custom module isn't working

### ISSUE THREAD

**Issue by vnourdin** [EndeavourOS-Community-Editions/sway#24]
The weather custom Waybar module seems broken, as spotted in #22.

I don't entirely understand how Waybar's modules works, but the [weather.sh](https://github.com/EndeavourOS-Community-Editions/sway/blob/main/.config/waybar/scripts/weather.sh) script takes argument but I don't see any arg passed from the Waybar config.

**Comment by OdiousImp2604** [comment]
Yep. Commented it out for now. Been a little busy so haven't found an alternative.

**Comment by OdiousImp2604** [comment]
I was thinking of replacing the weather script with with this. https://gist.github.com/sveatlo/d2fb837758088a98ad727f56072d6f1c. excluding the geolaction API. 

All credit to svealto

**Comment by ringo32** [comment]
Could use wttr.in?

**Comment by OdiousImp2604** [comment]
> Could use wttr.in?

Oo good idea I will look at that.

**Comment by ringo32** [comment]
in my lxqt panel is like : echo $(curl  https://wttr.in/Pelt:Lommel:Hamont?format=4 )	
with this  : echo $(curl  https://wttr.in/?format=4 )	  wil it choose the region not the exact place , could be a village beside :)

the 4 means also get symbols of wint  sunny night etc..

only bug it wil be also, sometimes are the servers overload some days then it get a error on the panel. 1M calls a day i believe.

**Comment by wouter9000** [comment]
I made a pull request to fix this issue but it got rejected without elaboration

**Comment by OdiousImp2604** [comment]
> I made a pull request to fix this issue but it got rejected without clarification
> 

I'm unsure who actually closed that. Sorry, let me take another look right now.

**Comment by OdiousImp2604** [comment]
> I made a pull request to fix this issue but it got rejected without clarification
> 

Now merged closing issue
