### ISSUE TITLE
System freezes after exiting suspend mode

### ISSUE THREAD

**Issue by vanarok** [EndeavourOS-Community-Editions/sway#27]
I installed the system about two weeks ago. My problem is that the system for the second day after coming out of suspend mode does not respond to keyboard presses, TTY change does not work either. I only see the lock menu on the screen. I tried to reproduce the problem manually but it does not work. I put the system to suspend before going to sleep and then resume in the morning. My hardware is a Dell latitude 3510 laptop, i5 10210u, it has no video card other than the integrated one. My system has a swap partition (8gb), btrfs file system and encryption enabled. I manually checked suspend, hybrid-sleep, hibernation and suspend then hibernation via systemctl. There is no problem with resuming the laptop.

**Comment by vanarok** [comment]
[eos-log-tool.logs.tar.gz](https://github.com/EndeavourOS-Community-Editions/sway/files/8440232/eos-log-tool.logs.tar.gz)

**Comment by vanarok** [comment]
https://raw.githubusercontent.com/endeavouros-team/snippets/main/BTRFS-encrypted-resume-creator 
Can i use this script on the default EndeavourOS Sway system to fix the proplem?

**Comment by vanarok** [comment]
Installed the LTS kernel and updated the bios. Currently the problem does not occur.

**Comment by OdiousImp2604** [comment]
Sorry for not responding.  I'm glad to see your problem has mended. What kernel were you using beforehand.

**Comment by vanarok** [comment]
> Sorry for not responding. I'm glad to see your problem has mended. What kernel were you using beforehand.

Linux-zen

**Comment by OdiousImp2604** [comment]
Just checking if the problem has appeared again or not? I am not sure what the problem is but if changing kernel's helped then it is most likely that.

**Comment by vanarok** [comment]
I have not encountered this problem with the linux-lts kernel anymore.
