### ISSUE TITLE
[sway] volume control does not work out of the box

### ISSUE THREAD

**Issue by wouter9000** [EndeavourOS-Community-Editions/sway#29]
Seems like pamixer is not installed out of the box.

**Comment by OdiousImp2604** [comment]
@killajoe Any idea? I believe it is a part of the base packages?

**Comment by killajoe** [comment]
pamixer does not work with pipewire..

**Comment by killajoe** [comment]
do sway setup using it in scripts? if so you need to replace with something else ;)

**Comment by killajoe** [comment]
amixer p.e .. 
https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/main/.config/i3/scripts/volume

**Comment by ns-ian** [comment]
@killajoe pipewire-pulse appears to be installed by default, installing pamixer solved this for me (volume control keys were also not working out of the box for me)

**Comment by OdiousImp2604** [comment]
This is also what solved it for me. Pamixer does seem to work for me?

**Comment by killajoe** [comment]
> This is also what solved it for me. Pamixer does seem to work for me?

could be it is fixed.. it was not working before.. 
![2022-08-22_10-08](https://user-images.githubusercontent.com/16797647/185871724-9e53ce2f-7ca9-433f-ad1f-f5cb4d8be6f8.png)
yea confirmed it is working ;) 
So add itb into packages and pm to get configs for installed updated..

**Comment by OdiousImp2604** [comment]
Okay. 👍

**Comment by killajoe** [comment]
> Okay. +1
> 
> Do you want me to add a post in the forum or you?

not for me but for the sway edition to get updated ;)

**Comment by rjd22** [comment]
My recommendation would be controlling pactl directly. This way there is no need for the pamixer package:

```
# audio control
set $sink_volume pactl get-sink-volume @DEFAULT_SINK@ | grep '^Volume:' | cut -d / -f 2 | tr -d ' ' | sed 's/%//'
set $source_volume pactl get-source-volume @DEFAULT_SOURCE@ | grep '^Volume:' | cut -d / -f 2 | tr -d ' ' | sed 's/%//'
set $volume_down $(pactl set-sink-volume @DEFAULT_SINK@ -5% && $sink_volume)
set $volume_up $(pactl set-sink-volume @DEFAULT_SINK@ +5% && $sink_volume)
set $volume_mute $(pactl set-sink-mute @DEFAULT_SINK@ toggle && pactl get-sink-mute @DEFAULT_SINK@ | sed -En "/no/ s/.*/$($sink_volume)/p; /yes/ s/.*/0/p")
set $mic_mute $(pactl set-source-mute @DEFAULT_SOURCE@ toggle && pactl get-source-mute @DEFAULT_SOURCE@ | sed -En "/no/ s/.*/$($source_volume)/p; /yes/ s/.*/0/p")
```

**Comment by killajoe** [comment]
> ...<SNIP!!>...

ha ha like the snip!

**Comment by OdiousImp2604** [comment]
I need to try this out! Unfortunately, I will admit, I don't actually understand it but if it works fantastic.

Joe, would this be a valid alternative? My only concern is that it might make the config a bit confusing.

**Comment by rjd22** [comment]
I've been running it for a few months now without issues.

It's an adaptation of the Manjaro sway implementation if I remember correctly.

**Comment by killajoe** [comment]
> Joe, would this be a valid alternative? My only concern is that it might make the config a bit confusing.

confusing a bit indeed using sed inside what will be hard to edit if users want to change,, but you could add it and leave the current as option commented or the other way around.. so it is possible to switch between and do testing on it by users ?

**Comment by OdiousImp2604** [comment]
> as option commented or the other way around.. so it is possible to switch between and do testing on it by users ?

Yes that seems a good idea



> I can make a PR if you want to.

That would be incredibly helpful since I'm busy now. I have tried it on my install and it works perfectly. Would you mind as Joe said comment out the old one instead of removing it.

**Comment by rjd22** [comment]
Added the PR. Feel free to test it :)

https://github.com/EndeavourOS-Community-Editions/sway/pull/40
