### ISSUE TITLE
Scaling for high resolutions on the login manager

### ISSUE THREAD

**Issue by ghost** [EndeavourOS-Community-Editions/sway#31]
I must admit I do not even know what login manager is being used, all I can do is describe the problem at this point;

I run a 4k screen on my laptop. Scaling works near perfect everywhere out of the box. Except for in the login manager where there seems to be no scaling at all (1x). This doesn't look too sexy.

Once I login, sway perfectly scales for my monitor.

Edit: obviously this is not a major issue and all functionality is still in place!

**Comment by OdiousImp2604** [comment]
We use SDDM. I also have no idea how to fix this but I will keep the issue open of someone does!

**Comment by killajoe** [comment]
https://wiki.archlinux.org/title/SDDM#Enable_HiDPI

**Comment by killajoe** [comment]
i do not think we can do that like having per default a sit could cause issues the other way around

**Comment by wouter9000** [comment]
I was thinking we could do something like this:

run 
`swaymsg -t get_output` and read the "scale factor" from there. 

If the scale factor of the primary output is > 1.5, we set HiDPI for SSDM.

If I understand it correctly, there is a script that is run when setting up the system. Has sway already executed at that point so that we could actually use swaymsg? If this is the case we could add something like I described above.

I'm just thinking out loud; it would be awesome if we can get everything to work right out of the box for (laptops with) high dpi displays.

**Comment by mmedum** [comment]
I just installed sway through the iso, and was asked whether I had a hiDPI display on my laptop - would it be possible to inject something into the sddm file before doing the first reboot after installation? 
Is the community editions actually running any code before the first boot as part of finishing installation?

**Comment by mmedum** [comment]
I just installed sway through the iso, and was asked whether I had a hiDPI display on my laptop - would it be possible to inject something into the sddm file before doing the first reboot after installation? 
Is the community editions actually running any code before the first boot as part of finishing installation?

**Comment by killajoe** [comment]
https://github.com/EndeavourOS-Community-Editions/sway/blob/main/set_once.sh
runs on first login but not before login or even before sddm starts..
This would need systemd service to be created an d setup.. 
Possible yes but not really something we should do..
May there is a way to have sddm doing such with the config?

 https://github.com/endeavouros-team/eos-sddm-theme

**Comment by mmedum** [comment]
> https://github.com/EndeavourOS-Community-Editions/sway/blob/main/set_once.sh runs on first login but not before login or even before sddm starts.. This would need systemd service to be created an d setup.. Possible yes but not really something we should do.. May there is a way to have sddm doing such with the config?
> 
> https://github.com/endeavouros-team/eos-sddm-theme

We could set it through set_once.sh then? So after the first login, run the check for hiDPI and if true, add the change to the sddm config file? They would result in one login without sddm, but the rest setup correctly.
