### ISSUE TITLE
Firefox windows switch to floating when the page title contains the word "Library"

### ISSUE THREAD

**Issue by mikedal** [EndeavourOS-Community-Editions/sway#37]
I think this is a bug in this line in the config:
https://github.com/EndeavourOS-Community-Editions/sway/blob/70ea1c36e5566ba41f7b826a54ca4473ee679e19/.config/sway/config.d/application_defaults#L40
I'm not sure what the intent was of the line, but it seems to me that it's being applied more broadly than it should be. For example, when I open the [Python Standard Library documentation](https://docs.python.org/3/library/index.html), my window is toggled to floating. This also happens for any other web page with the word Library in the title.
I was able to work around the issue by commenting out the line, but without knowing why it was added, I don't want to open a PR doing so.

**Comment by OdiousImp2604** [comment]
Sorry I took so long replying. I have no idea. 

I cannot think of any reason why I would've added that.

Has anything changed elsewhere when you've commented it out?

**Comment by mikedal** [comment]
I haven't noticed any other changes. My windows did stop changing to floating when I didn't want them to.

**Comment by OdiousImp2604** [comment]
Cool. Neither have I. I will get rid of it.

**Comment by vnourdin** [comment]
This set to floating the "Library" window, which contains your history.
Can't we change the filter to make it strict, like in regex `^Library$` to avoid matching windows with just "Library" being part of the title ?

**Comment by vnourdin** [comment]
It is the window opened to "manage history" as explained [here](https://support.mozilla.org/en-US/kb/browsing-history-firefox).
![](https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2019-10-10-03-47-24-4220d1.png)

I rarely use it but it's better to have it floating, **if** we find a way to stop impacting other windows. I have the same problem with PayPal payment page that I like to have floating but without a strict filter, every PayPal relative tabs make my firefox floating.

**Comment by killajoe** [comment]
unmaintained needs contributors or maintainer
