### ISSUE TITLE
pipewire instead of pulse

### ISSUE THREAD

**Issue by notwidow** [EndeavourOS-Community-Editions/sway#43]
Hi, can you please switch from pulseaudio to pipewire?

**Comment by mmedum** [comment]
Sorry for tagging you here @OdiousImp2604, but is this something that could be of interest? From what I can see, most changes needs to happen on waybar, as standard endavouros uses pipewire?

**Comment by mmedum** [comment]
> Hi, can you please switch from pulseaudio to pipewire?

If you have not done it already, here is a write up of how it could be done: https://discovery.endeavouros.com/audio/pipewire/2021/09/ 🙂

**Comment by OdiousImp2604** [comment]
> Sorry for tagging you here @OdiousImp2604, but is this something that could be of interest? From what I can see, most changes needs to happen on waybar, as standard endavouros uses pipewire?

No problem! Feel free to tag me always! The module of waybar is simply called pulseaudio. The actual changing of volume occurs with pamixer. I not what I would have to change for it pipewire?

**Comment by primeapple** [comment]
> No problem! Feel free to tag me always! The module of waybar is simply called pulseaudio. The actual changing of volume occurs with pamixer. I not sure what I would have to change for it pipewire?

I think we control the volume with `pactl` instead of `pamixer` with this PR: https://github.com/EndeavourOS-Community-Editions/sway/pull/40

**Comment by mmedum** [comment]
> I think we control the volume with `pactl` instead of `pamixer` with this PR: #40

Good catch! Then we just need to test a new waybar module and remove the pamixer installation? On the newest endeavouros installation, pulseaudio is not installed anyway 🙂

**Comment by mmedum** [comment]
> Good catch! Then we just need to test a new waybar module and remove the pamixer installation? On the newest endeavouros installation, pulseaudio is not installed anyway 🙂

Actually I am using the pulseaudio extension for waybar, pipewire and pactl, which works wonderfully already.

**Comment by notwidow** [comment]
> > Good catch! Then we just need to test a new waybar module and remove the pamixer installation? On the newest endeavouros installation, pulseaudio is not installed anyway 🙂
> 
> Actually I am using the pulseaudio extension for waybar, pipewire and pactl, which works wonderfully already.

i am also using pactl and pipewire with no issue but one minor maybe you will see also.. with pipewire and pactl there is no limit of volume for max level. just increase the volume and keep it increasing and you will see the volume will go above 1000% up and wont stop.. haha i reached it to almost 1300% ... which needs to be fixed for it to not go above 100%>>>>

**Comment by mmedum** [comment]
> i am also using pactl and pipewire with no issue but one minor maybe you will see also.. with pipewire and pactl there is no limit of volume for max level. just increase the volume and keep it increasing and you will see the volume will go above 1000% up and wont stop.. haha i reached it to almost 1300% ... which needs to be fixed for it to not go above 100%>

My guess is that pactl is allowing that to happen - I will do some testing today, maybe there command can be changed to something smarter.

> when it goes above 100% it damages the hardware... so you might want to limit it... and for your information this issue is with pipewire from the start... >

Orh I know, my comment was about making sure, that waybar is showing the volume correctly, when you use pipewire.. :)
