### ISSUE TITLE
Changes to ~/.profile

### ISSUE THREAD

**Issue by rantnar** [EndeavourOS-Community-Editions/sway#46]
Hi. I've noticed that we export some flags in ~/.profile. For example to launch firefox using wayland. Problem is, for me anyway that it does not work. As far as I know arch is looking for .bash_profile, .bash_login, and .profile in that order. So if it finds .bash_login it does not read .profile file.

I noticed this behaviour when firefox was not scaling well on my hidpi display. Blurry UI and fonts. I checked and it was running on xwayland instead of wayland. I fixed it by exporting MOZ_ENABLE_WAYLAND=1 in the .bash_profile file instead of .profile.

Please correct me if I'm wrong and commands in .profile are executed and this is some weird bug.

**Comment by OdiousImp2604** [comment]
This is a weird occurrence we've had for a long time. For some people, it works in .profile; for some, it doesn't but we have never actually troubleshooted it before. I can add in a .bash_profile file if that helps?

**Comment by catterdx** [comment]
When installing the EndeavourOS community edition using the ISO, after the installation is complete, there is no command like 'source ~/.profile' in the 'system-wide startup files' located in /etc/skel/, /etc/bash.bashrc, /etc/profile, /etc/profile.d/*, ~/.bash_profile, and ~/.bashrc. Additionally, in the /usr/share/sddm/scripts/wayland-session file, there doesn't seem to be a clear mention of 'source ~/.profile' regarding the handling of bash. In the end, I manually added this command to the wayland-session file.

https://github.com/sddm/sddm/issues/1551

**Comment by killajoe** [comment]
unmaintained needs contributors or maintainer
