### ISSUE TITLE
Shutdown hangs at "A stop job is running for simple desktop display managaer"

### ISSUE THREAD

**Issue by yangvw** [EndeavourOS-Community-Editions/sway#47]
Per https://forum.endeavouros.com/t/shutdown-hangs-at-stop-job-for-simple-desktop-display-manager/37627, it seems that the upstream version of sddm (aur/sddm-git) fixed the issue, so it should be installed by default instead

**Comment by fhoekstra** [comment]
I guess SDDM has since pushed the fix to the Arch repo as this does not happen on my install. I installed from the Cassini live boot in September.

**Comment by killajoe** [comment]
unmaintained needs contributors or maintainer
