### ISSUE TITLE
Android devices connected through usb isnt recoginized

### ISSUE THREAD

**Issue by i2sage** [EndeavourOS-Community-Editions/sway#51]
Android devices does not connect and doesnt show in file managers. i tried installing adb but it still did not show in file explorer, so i tried it in terminal. i can access the device through terminal but only in read mode (idk of this is eos issue or not). i tried the fixes in community forum still not fixed.

**Comment by negativeExponent** [comment]
install gvfs-mtp

**Comment by killajoe** [comment]
unmaintained needs contributors or maintainer
