### ISSUE TITLE
Screensharing does not work (Firefox & Chromium)

### ISSUE THREAD

**Issue by fhoekstra** [EndeavourOS-Community-Editions/sway#54]
I had a problem on my install that I could not do screensharing in Firefox and Chromium, despite setting all the env vars launch arguments and about:configs and chrome://flags that I could find, in several places on my machine.

When going through the [excellent xdg-desktop-portal-wlr troubleshooting guide](https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist), I found out that there was a problem with the xdg-desktop-portal. Instead of just exporting the XDG_CURRENT_DESKTOP env var, we need to explicitly pass it along to the systemd and dbus environments.

#52 fixes this

**Comment by killajoe** [comment]
unmaintained needs contributors or maintainer
