### ISSUE TITLE
Installing on non arch distro

### ISSUE THREAD

**Issue by marcandru** [EndeavourOS-Community-Editions/sway#55]
Hello!

I was just wondering is this is possible to install on another distro, I'm using Fedora. I think the only thing I would need to change is maybe the package name in the text file, but I'm not exactly sure?

**Comment by fhoekstra** [comment]
Fedora has its own Sway spin, but I'm not sure if that one can be installed manually though.

A quick search for `pacman` (Archlinux' package manager) in this repo shows the things that will definitely need changing to run on Fedora. There are probably more things that will not work.
https://github.com/search?q=repo%3AEndeavourOS-Community-Editions%2Fsway%20%20pacman&type=code

I would probably install Fedora Sway spin, or manually install the required programs into your existing system, and then copy config from here if  it's the look you're after.
Why are you interested in this Sway setup specifically?

**Comment by marcandru** [comment]
I licked the theming of sway edition, so I was trying to see if I could get it over on Fedora. If it's just the configs I need to copy then I'll do that

**Comment by fhoekstra** [comment]
Yep, most of what you're interested in will be in .config/sway and .config/waybar

**Comment by killajoe** [comment]
unmaintained needs contributors or maintainer
