### ISSUE TITLE
Brightness control of waybar

### ISSUE THREAD

**Issue by hm-sh** [EndeavourOS-Community-Editions/sway#7]
in /.config/waybar/config

```
"backlight#icon": { 
"format": "{icon}",    	
"format-icons": [""],    	
"on-scroll-down": "brightnessctl -c backlight set 5%",
"on-scroll-up": "brightnessctl -c backlight set +5%-"
},

"backlight#value" :{ "format": "{percent}%",
"on-scroll-down": "brightnessctl -c backlight set 5%", 
"on-scroll-up": "brightnessctl -c backlight set +5%"
}
```
Right now scrolling down set the brightness levels at 5%
"on-scroll-down": "brightnessctl -c backlight set 5%-"
"on-scroll-up": "brightnessctl -c backlight set +5%"
gives scrolling on the brightness the intended effect.

**Comment by OdiousImp2604** [comment]
Cool! Sorry I took so long to respond. Change will be made.

**Comment by OdiousImp2604** [comment]
Done! Thank you
