### ISSUE TITLE
[Potential Bug] Ethernet stops working after a few days.

### ISSUE THREAD

**Issue by worldpe** [EndeavourOS-Community-Editions/sway#8]
I am filing this as a bug of this edition of EndeavourOS because I am not sure what else could be the result of this. Essentially, the version of endeavourOS I use is this one. I have not checked if this applies to other versions for me as that would take quite a lot of time, and if you don't think that this could be contingent to this version, I can move this post elsewhere. However inexplicably, after about 3-5 days of use whenever I use this edition of EndeavourOS, the ethernet stop being recognized entirely. I have got it working again a few times after forum post scrawling, but it is just weird this one specific things randomly breaks after the same amount of time on fresh installs of this distro.

**Comment by OdiousImp2604** [comment]
Do you mind posting this on the forum? It seems to be a distro problem rather than one with the sway configs. The community will be happy to help over there!

forum.endeavouros.com
