### ISSUE TITLE
ISO script not working anymore [setup_sway_isomode.bash]

### ISSUE THREAD

**Issue by killajoe** [EndeavourOS-Community-Editions/sway#83]
https://github.com/EndeavourOS-Community-Editions/sway/blob/main/setup_sway_isomode.bash
Using this on ISO is failing cause the script is not running fully.. it does give specific error:

```
2024-09-11 - 21:52:21 [6]:     .. Running QList("/tmp/user_commands.bash", "joe") 
2024-09-11 - 21:52:21 [6]: [PYTHON JOB]: "/tmp/user_commands.bash: line 7: syntax error near unexpected token `newline'\n" 
2024-09-11 - 21:52:21 [6]: [PYTHON JOB]: "/tmp/user_commands.bash: line 7: `<!DOCTYPE html>'\n" 
2024-09-11 - 21:52:21 [6]:     .. Target cmd: QList("/tmp/user_commands.bash", "joe") Exit code: 2 (no output) 

```
`pacman -S --noconfirm --noprogressbar --needed --disable-download-timeout $(< ./sway/packages-repository.txt)`
should be this:
`pacman -S --noconfirm --noprogressbar --needed --disable-download-timeout - < ./sway/packages-repository.txt`

?

**Comment by BluishHumility** [comment]
> https://github.com/EndeavourOS-Community-Editions/sway/blob/main/setup_sway_isomode.bash

That's not the right URL. You have to use the raw version, or it pulls in a bunch of html info that messes it up.

Try with this URL:

```
https://raw.githubusercontent.com/EndeavourOS-Community-Editions/sway/main/setup_sway_isomode.bash
```

**Comment by killajoe** [comment]
Now I see could be I used the non raw url indeed.
In VM gtkgreet is not starting, i bet is hat's a VM  thing? (Virtualbox)

**Comment by BluishHumility** [comment]
I'm not sure about Virtualbox, but to get it working in VMWare I had to downgrade a lot of packages:
```
sudo downgrade cage greetd-regreet sway wlroots
````

I'm pretty sure the reason `sway` and `wlroots` need to be downgraded is this vmwgfx issue:

https://github.com/swaywm/sway/issues/8189

https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3850

The other packages need to be downgraded due to dependency relationships with `sway`, `wlroots`, or each other.

These are the versions that got it working for me when I was testing:

```
cage - 0.1.5-1
greetd-regreet - 0.1.0-1
sway - 1:1.8.1-5
wlroots - 0.16.2-2
```
```
> :: Retrieving packages ...
cage-0.1.5-1-x86_64				22.7 KiB	28.1 KiB/s 00:01
greetd-regreet-0.1.0-1-x86_64	1206.0 KiB	967 KiB/s 00:01
sway-1:1.8.1-5-x86_64			5.1 MiB		3.33 MiB/s 00:02
wlroots-0.16.2-2-x86_64			392.0 KiB	355 KiB/s 00:01
loading packages ...
warning: downgrading package greetd-regreet (0.1.1-3 => 0.1.0-1)
warning: downgrading package sway (1:1.9-5 => 1:1.8.1-5)
resolving dependencies ...
looking for conflicting packages ..
: : wlroots-0.16.2-2 and wlroots0.17-0.17.4-3 are in conflict. Remove wlroots0.17? [y/N] y

Package (5)		Old Version New Version Net Change

wlroots0.17		0.17.4-3 				-1.37 MiB
cage						0.1.5-1 	0.06 MiB
greetd-regreet	0.1.1-3 	0.1.0-1 	0.04 MiB
sway			1:1.9-5		1:1.8.1-5 	0.02 MiB
wlroots0					0.16.2-2 	1.29 MiB

Total Installed Size:	10.81 MiB
Net Upgrade Size:		0.05 MiB

: : Proceed with installation? [Y/n]
```

After that, restart the display manager and everything seems to work normally.

**Comment by killajoe** [comment]
using latest virtualbox? it just updted and sinc ei can not change any setting on it anymore.. so i can`t check on virtualbox at the moment

**Comment by BluishHumility** [comment]
> using latest virtualbox?

No, I have not tested Virtualbox at all. Those downgrades got it working with VMWare.

Complete installation > reboot > switch to TTY when display manager fails to load > downgrade packages > restart display manager and log in.

I'm not sure what the Virtualbox issue is; it sounds like it might be something else.
