### ISSUE TITLE
enable greetd in ISO script should not be needed

### ISSUE THREAD

**Issue by killajoe** [EndeavourOS-Community-Editions/sway#85]
```
# Enable the Greetd service
echo "Enabling the Greetd service..."
systemctl enable greetd.service
```

in:
https://github.com/EndeavourOS-Community-Editions/sway/blob/main/setup_sway_isomode.bash

should not be needed, calamares supports greetd:
https://github.com/endeavouros-team/calamares/blob/9ed727a129228fef022f4125cf0deaf20e1581bb/data/eos/modules/services-systemd.conf#L28

I see also greetd is failing to start under virtualbox even with 3d enabled.

**Comment by killajoe** [comment]
ah i see ;)
As the bash iso script is running late in the install process it does not have greetd installed before the systemd module is running..:

https://github.com/endeavouros-team/calamares/blob/9ed727a129228fef022f4125cf0deaf20e1581bb/data/eos/settings_online.conf#L80

we should consider moving the modul after the systemd module..

**Comment by BluishHumility** [comment]
Yes, that's right--when Calamares checks for display managers, Greetd hasn't been installed yet.

![image](https://github.com/user-attachments/assets/800c64ac-dd2c-4779-9835-caa4d69c0a32)

> we should consider moving the module before the systemd module..

Do you mean `user_commands.bash` will run before the systemd module in that case?

**Comment by killajoe** [comment]
> Do you mean `user_commands.bash` will run before the systemd module in that case?

yes simply change order in https://github.com/endeavouros-team/calamares/blob/9ed727a129228fef022f4125cf0deaf20e1581bb/data/eos/settings_online.conf#L80 this thats zthe module schedule used.. but in general it could be also an issue if user have a script handling systemd-services alrerady handled by the module it could override stuff.. like the issue i have with cosmic, were you have greetd installed but it needs the cosmic-greeter enabled instead..  so seems smarter to have it this way and add the lines into the script like it is now..

**Comment by BluishHumility** [comment]
> so seems smarter to have it this way and add the lines into the script like it is now

I think it is fine, too. It might be better that `user_commands.bash` runs after all the Calamares stuff is already finished because it's simple, and easy for the user to understand. They do not need to have any knowledge about what Calamares modules will run after their script, and what those modules will change or not change.

Once we move Sway back to the default installs, we won't need to worry about relying on `user_commands.bash` anymore anyway. :wink:
