### ISSUE TITLE
layout is not layouting 

### ISSUE THREAD

**Issue by potatoboi120-forge** [EndeavourOS-Community-Editions/sway#93]
hi i wanted to have arabic in my layout i used the  `.config/sway/config.d/input` and didn't work 
```
input "type:keyboard" {
    xkb_layout "us,ara"
    xkb_options "grp:win_space_toggle"
}

```
and i tried
```
input * {
    xkb_layout "us,ara"
    xkb_options "grp:win_space_toggle"
}
```
i even added the cod to `.config/sway/config` and no work i dont know why

**Comment by potatoboi120-forge** [comment]
i need help fast i really want to use it as my main wm

**Comment by BluishHumility** [comment]
> i used the `.config/sway/config.d/input` and didn't work
> 
> ```
> input "type:keyboard" {
>     xkb_layout "us,ara"
>     xkb_options "grp:win_space_toggle"
> }
> ```

This looks fine as far as I can tell, except by default this keybinding is assigned to something else.

https://github.com/EndeavourOS-Community-Editions/sway/blob/main/.config/sway/config.d/default#L143

Try commenting out the binding in the Sway config to see if it is interfering with your custom `xkb_options` binding.

Alternately, try changing your `xkb_options` binding to something else. The commented example code in the `input` file has been tested and confirmed to work with <kbd>Alt</kbd>+<kbd>Shift</kbd>.

```
# Toggle between keyboard layouts. This example has the "us" and "gb"
# keyboard layouts, and uses Alt+Shift to toggle between them.
input "type:keyboard" {
    xkb_layout "us,gb"
    xkb_options "grp:alt_shift_toggle"
}
# Assign the same binding to "pkill -RTMIN+1 waybar" to send signal to
# the Waybar keyboard module (so the module shows the updated layout).
# This example uses Alt + left Shift.
bindsym Alt+Shift_L exec "pkill -RTMIN+1 waybar"
```

Uncomment the example code and change `gb` to `ara` to test if it works with this binding.

**Comment by potatoboi120-forge** [comment]
i tried the defualt config and didnt work its not the keybinding but the full comand is not working

**Comment by potatoboi120-forge** [comment]
and i did the [forum page](https://forum.endeavouros.com/t/sway-wont-let-me-change-keyboard-layouts/13736/65?page=2) didnt help me either maybe the proplem is i came from eos i3

**Comment by potatoboi120-forge** [comment]
im sure now the proplem is the input config is not working  cs idid
```
input "type:keyboard" {
    xkb_layout "ara"
    xkb_options "grp:alt_shift_toggle"
```
 and nothing work

**Comment by potatoboi120-forge** [comment]
i solved the problem it was the
```
# Set keyboard layout and variant based on current system settings
exec_always {
   'swaymsg input type:keyboard xkb_layout "$(localectl status | grep "X11 Layout" | sed -e "s/^.*X11 Layout://")"'
    'swaymsg input type:keyboard xkb_variant "$(localectl status | grep "X11 Variant" | sed -e "s/^.*X11 Variant://")"'
} 
```
it was doing somthing in the system after noting it i can write arabic again

**Comment by potatoboi120-forge** [comment]
thank you so much and i hope u the best and this wm
